### ISSUE TITLE
Azure App Service Extension

### ISSUE THREAD

**Issue by jcramer** [Azure/batch-shipyard#153]
I'm trying to install the batch-shipyard extension in Azure App Service using the instructions below with Azure Functions.  It doesn't work, fails on installation. The tutorial shows Batch-Shipyard v2.6 and maybe there were breaking changes for v3.x?

https://github.com/Azure/batch-shipyard/blob/master/docs/60-batch-shipyard-site-extension.md

**Comment by alfpark** [comment]
This may be due to the app service not being able to install the package within the time limits (if the service plan you specified is underpowered).

Try the following:
1. Load Kudu, go to `Debug console` and select `CMD`
2. Navigate to `D:\home\SiteExtensions\batch-shipyard`
3. Run the command `install.cmd`. Let this command run to completion (it may take a long time).
4. Restart your site.
5. To verify: Re-load Kudu, go back to the `Debug console`, select `CMD` and then run `%BATCH_SHIPYARD_CMD% --version`. There will be a delay, but you should see the version in the output.

**Comment by jcramer** [comment]
Thanks! it installed and it now works as intended.
