### ISSUE TITLE
publish batch-shipyard to pypi

### ISSUE THREAD

**Issue by lgilz** [Azure/batch-shipyard#192]
I would like to install batch-shipyard via pypi, e.g. `$ pip install batch-shipyard`. Is that something you plan to do at some point?

**Comment by alfpark** [comment]
Because of all of the system-level dependencies needed to ensure everything works, I have opted not to publish to pypi and instead have it be install script driven. Additionally, niceties such as the docs/recipes being available in an obvious location (i.e., where you cloned or unpacked) would go away.

That being said, we're open to publishing it on pypi. Scenarios such as automated deployment or integration into larger stacks would be easier through pypi. Do you have any other scenarios in mind that I'm missing?

**Comment by alfpark** [comment]
I've created a workitem #196. I performed a review of what would be required. Due to `pykwalify` still using `pyyaml`, I can't do this yet in a clean manner that would work with setup.py.
