### ISSUE TITLE
vm_count 0 ignored when autoscale formula specified

### ISSUE THREAD

**Issue by gregjhogan** [Azure/batch-shipyard#208]
I want to create a pool with zero nodes initially and a custom auto-scale formula.  When I create the pool it spins up nodes (ignoring my `dedicated` and `low_priority` specified).  They are respected when I setup auto-scaling using  `scenario: pending_tasks`.

```
pool_specification:
  id: test-pool
  vm_configuration:
    platform_image:
      offer: UbuntuServer
      publisher: Canonical
      sku: 16.04-LTS
  vm_count:
    dedicated: 0
    low_priority: 0
  vm_size: Standard_F8
  max_tasks_per_node: 8
  resize_timeout: 00:15:00
  autoscale:
    evaluation_interval: 00:05:00
    formula: |
      maxTasksPerNode = 8;
      maxTargetLowPriority = 5000;
      pendingTasks = max($PendingTasks.GetSample(1));
      requiredNodes = pendingTasks / maxTasksPerNode;
      lowPriorityNodes = (pendingTasks > 0 && requiredNodes < 1) ? 1 : requiredNodes;
      lowPriorityNodes = min(maxTargetLowPriority, lowPriorityNodes);
      $TargetLowPriorityNodes = min($CurrentLowPriorityNodes + 25, lowPriorityNodes);
      $NodeDeallocationOption = requeue;
  reboot_on_start_task_failed: true
  attempt_recovery_on_unusable: true
  block_until_all_global_resources_loaded: true
  transfer_files_on_pool_creation: true
```

**Comment by alfpark** [comment]
When the pool is created, how many dedicated and low priority nodes is it spun up with? Can you use Batch Labs or the Portal to inspect if there is an autoscale formula attached to the pool?

**Comment by gregjhogan** [comment]
@alfpark my formula above is applied to the pool, and that formula limits it to only increasing the low priority node count by a max of 25.  If you create a pool using the above config you will find it spins up 25 low priority nodes and 0 dedicated nodes on creation, and then auto-scaling will spin them back down shortly after.

**Comment by alfpark** [comment]
Autoscale enabled pools cannot have target counts specified on creation. However, an evaluation may be immediately performed when the pool is created.

Your autoscale formula is triggering this resize on create because you have a problematic line here:
```
pendingTasks = max($PendingTasks.GetSample(1));
```

When there are no samples in the `$PendingTasks` vector, then the result is undefined. When you apply `max()` to it, then it evaluates to something meaningless (i.e., `nan`). If you follow the logic of your autoscale formula to `$TargetLowPriorityNodes`, then you will see it trying to evaluate `min(0 + 25, 5000)` which will result in `25`.

If you execute `pool autoscale lastexec`, you would see something like:
```
2018-06-07 07:11:19.114 INFO - autoscale result: $TargetDedicatedNodes=0;$TargetLowPriorityNodes=25;$NodeDeallocationOption=requeue;lowPriorityNodes=5000;maxTargetLowPriority=5000;maxTasksPerNode=8;pendingTasks=nan;requiredNodes=nan
2018-06-07 07:11:19.115 INFO - last autoscale evaluation: 2018-06-07 14:10:33.362967+00:00
```

You could fix this by ensuring that `pendingTasks` gets assigned something valid:
```
pendingTasks = max(0, val($PendingTasks.GetSample(1), 0));
```

Or by using one of the built-in [autoscale scenarios](http://batch-shipyard.readthedocs.io/en/latest/30-batch-shipyard-autoscale/) instead of custom defining your own.

Note: in general, the use of `GetSample(1)` is not recommended because it's impossible to know when this sample was taken. It's better to give time interval lookbacks to `GetSample()` instead. Given a small enough time period, this could also result in an undefined vector as well, so you still need to take care of this possibility.

**Comment by alfpark** [comment]
This is a great suggestion. I'll open up an issue to track.

**Comment by gregjhogan** [comment]
Yeah we are already on a premium container registry, which currently has a limit of 100 MBps and 10K read ops per minute (seems kind of low!), which is pretty easy for us to hit since our docker images are kind of big.  Thanks!
