### ISSUE TITLE
Tasks allocated to autoscaled pools are randomly killed and restarted

### ISSUE THREAD

**Issue by whataride** [Azure/batch-shipyard#218]
Here is what we did:

1. Allocate an empty pool with 0 dedicated VMs and 0 low pri VMs. The pool has autoscaling turned on based on active_tasks; upon scaling up, only dedicated VMs will be used:

![image](https://user-images.githubusercontent.com/6028927/41868423-e84d85a4-786a-11e8-8073-5e483716c9fa.png)

2. Submit long-running tasks to the pool, which triggers autoscaling
3. We saw the tasks are stopped for no reason and then restarted. Looks like the nodes are of low-pri

Any idea about such behavior? Maybe we overlooked some of the settings?

**Comment by alfpark** [comment]
How many tasks are you submitting?

Typically, if your scenario is based on `active_tasks`, you will want your `node_deallocation_option` to be `taskcompletion`.

**Comment by whataride** [comment]
I submitted 3. The pool was able to scale up according to the # of tasks (1 task per node).

We will try `taskcompletion`, but do you think that will explain the unexpected behavior?

**Comment by alfpark** [comment]
I think that explains the behavior you are observing.

Note that running tasks do not count towards the active task metric (you need to use the `pending_tasks` scenario for that). So take these hypothetical evaluations with your maximums and scenario setting:

1. Everything is at 0.
2. Submit 3 tasks.
3. Autoscale evaluation occurs. Active tasks is 3, triggering a resize up and allocation of 3 nodes.
4. Nodes begin allocating.
5. Autoscale evaluation occurs. Nothing has changed as no tasks have yet been picked up as nodes are still allocating.
6. First node becomes ready and idle.
7. 1 task is scheduled to that node. Active task count is now 2.
8. Second node becomes ready and idle.
9. 1 task is scheduled to that node. Active task count is now 1.
10. Suppose the third node is taking much longer to come up.
11. Autoscale evaluation occurs. Active task count is 1. Because `node_deallocation_option` is set to `requeue`, 2 nodes are immediately reclaimed and *resize down* to 1 node is triggered to match the active task count. Let's say Batch reclaims a node running a task and the one still allocating. Your pool now contains 2 nodes in `leaving_pool` state and 1 in `running` state. Active task count is now 2 (due to the task requeue).

If your `node_deallocation_option` was set to `taskcompletion`, then Batch would not have immediately reclaimed nodes running tasks as they must complete first.

**Comment by alfpark** [comment]
Closing, please re-open if not resolved.

**Comment by whataride** [comment]
Setting `node_deallocation_option` to `taskcompletion` works! Thanks, @alfpark!
