### ISSUE TITLE
Incorrect job status (Completed instead of Disabled)

### ISSUE THREAD

**Issue by f-roche** [Azure/batch-shipyard#227]
Hi all,

at job YAML configuration level I set the `auto_complete: true` since I want the job to be set to `Completed` once all tasks are completed.
But I also set `exit_options` to `disable` from job `exit_conditions`, meaning if any of the tasks exit with a non-zero code job has to be set to `Disabled`.

Looks like it works almost well:

- job is set to `Completed` when all tasks have been executed successfully (exit code 0)
- job is set to `Disabled` once a task fails, except that after some time the job is finally set to `Completed`

This is an issue for since I need to know which jobs were executed successfully and which did not...

Is it related to my configuration? or Azure Batch configuration? or Batch-Shipyard?

Thanks.

**Comment by alfpark** [comment]
Job auto-completion takes precedence because once all tasks complete, then the job will move to completed state.

Conceptually, a job being "successful" (or not) is not something that is captured with job state. Individual tasks that make up a job do have this notion, and you should rely on translating your task states within a job to such a state indicating job-level "success".

You should remove your `exit_conditions` and keep your `auto_complete` set to `true`. Once your job reaches `Completed` state, you should enumerate your tasks and determine job "success." If you have a shell script or program executing `shipyard`, you can pass `--raw` for the command `jobs tasks list` and parse the json for any failing tasks.

To make this workflow easier, I'll add a `jobs tasks counts` command which will simply list task counts for jobs and will be `--raw` compatible.

**Comment by f-roche** [comment]
Thanks for your feedback.

I am not using the Batch-Shipyard CLI to monitor jobs/tasks but the Azure-Batch in Python with a single request. I may have to change it then to check status of all tasks of the job.

Just for asking, why not having the concept of job status (Completed/Failed) in its state?
It is probably because I don't have the big picture view but this is something that bugs me :)

Thanks

**Comment by alfpark** [comment]
If you are using the Batch Python SDK, then you can use the [task counts API](https://docs.microsoft.com/azure/batch/batch-get-resource-counts). This should fit your use-case well and is essentially what the proposed command in #228 will encapsulate. Batch Shipyard already uses this API, but it is surfaced indirectly with the `jobs stats` command and the output is difficult to parse programmatically.

As you know, a state of `Completed` either for task state or a job state does not imply success. For a task, it simply means that the task has completed execution. For a job, that means that the job has terminated. As a counterpoint to why Batch does not extend the success/failure result concept from tasks to jobs: how would the Batch service determine success or failure for a job containing 9 tasks that have succeeded but 1 task that has failed? Is the failure inconsequential to the job's success? The meaning and magnitude of the failed task depends upon the scenario which will vary between users and workloads. The logic for determining if a "job succeeded" is thus left to the user to determine from the collection of tasks.

**Comment by f-roche** [comment]
Thanks for this very detailed answer that make sense!
I'll have a look to the link you posted.
Thanks again.
