### ISSUE TITLE
Hb/Hc Support

### ISSUE THREAD

**Issue by alfpark** [Azure/batch-shipyard#277]
Support Hb/Hc VM sizes, support in any Batch account mode.

- [x] Allow CentOS-HPC 7.6
- [x] Changes required for SR-IOV IB
  - [x] Settings support
  - [x] Node prep
    - [x] Drop hard requirement for Intel MPI
    - [x] Catalog IB PKEY
  - [x] Task execution (and MPI)
    - [x] Drop forced Intel MPI
    - [x] Couple change with #287
    - [x] Auto add PKEYs to task env vars
- [x] OpenFOAM+IB+OpenMPI recipe
- [x] Doc updates
  - [x] Platform support
  - [x] Base readme

Stretch:
- [ ] Ubuntu 18.04 Packer script (on hold right now due to kernel issue)

**Comment by richardlock** [comment]
This would be excellent.  I was just looking at using Hb VMs in Azure Batch with OpenFOAM and OpenMPI (using this image: https://hub.docker.com/r/openfoam/openfoam6-paraview56).  Is there any workaround to use this with Batch Shipyard on Hb series currently please?  Thanks for your work on this tool.

**Comment by alfpark** [comment]
Unfortunately there's no workaround to provision currently, unless you're comfortable hacking up some of the code. Additionally due to the hard Intel MPI coupling (as prior gen hardware required it), task submission would most likely not work.

This is a high priority item and will be included in the next release.

In the meantime, you can use the openfoam recipe that exists with the H16r (assuming you don't need newer versions of openfoam) as a base for your scenario.

**Comment by richardlock** [comment]
Thanks.  I've got OpenFOAM-6 working with H16r VMs by creating a container based on yours but compiling OpenFOAM-6 with Intel MPI and copying into the final stage of the build.

https://github.com/richardlock/docker-openfoam6-paraview54-intelmpi/blob/master/Dockerfile

Is there a way to tell in Azure whether it is using the Infiniband network correctly with Intel MPI?  It runs successfully with mpirun, but the parallel runs get slower the more VMs/cores I add.  It might just be due to small cases which don't parallelise well, but I wanted to check that it wasn't falling back to using TCP and increasing latency.

Once the Hb series VM are supported with batch-shipyard, will it work with the pre-built https://hub.docker.com/r/openfoam/openfoam6-paraview56 image which has OpenMPI?  Thanks.

**Comment by alfpark** [comment]
It should not be using TCP if you run through Shipyard (the `I_MPI_*` env vars set should limit only to shm/dapl).

In theory, it should work with the pre-built image assuming the proper userland software is in the container. We will try to include testing against their public image.
