### ISSUE TITLE
Nodes and jobs getting stuck in weird states - disk full?

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#30]
I've been encountering issues with batch tasks and nodes getting stuck in weird states several hours after starting. Running short jobs works fine, but if run full job workloads (each job downloads and processes ~60GB of data each), nodes start getting stuck in "Waiting for start task" or "Idle", and tasks start getting stuck in "Running" or "Preparing" with no way for me to see the files for the specific task. I'm not sure if this is a batch-shipyard issue or an issue with Azure Batch itself. Could it have anything to do with running out of space on the node?

If it is a space issue, since I have `remove_container_after_exit` set to true, will this remove the data in `$AZ_BATCH_TASK_WORKING_DIR`? If not, is there a recommended way of removing this data? Since I'm running data fetch tasks, I have to egress most of this data to blob storage at the end of the task, so I can't remove the data before blobxfer runs.

**Comment by lediur** [comment]
Hmm, I just ran into a "no space left on device" error in one of my tasks, so that seems to at least confirm that this can be an issue. Apparently removing the container is not enough? I need to remove the job and the tasks as well?

**Comment by alfpark** [comment]
@lediur If the node runs our of disk space, this can cause issues for the agent running on the machine as you have seen. `remove_container_after_exit` is equivalent to the `--rm` switch given to `docker run`, meaning that the temporary container files are cleaned up and it's removed from `docker ps -a` as a stopped/exited container. If your container dumps data to `$AZ_BATCH_TASK_WORKING_DIR`, that is persisted to the host. This data is not automatically cleaned up because Azure Batch cannot possibly know when you would be done using data generated by your task.

There are a few solutions here:
1. Manually issue calls to delete the task or job after they have completed.
2. Create a task that depends on the prior task to clean up the other directories. You can see the entire Azure Batch directory structure with `$AZ_BATCH_ROOT_DIR`.
3. I can make code changes to support task retention constraints where you can specify some amount of delta time after a task completes to delete its data directory (i.e, `$AZ_BATCH_TASK_DIR`) automatically.
