### ISSUE TITLE
Very slow/stall copying when using Premuim storage

### ISSUE THREAD

**Issue by borisklug** [Azure/batch-shipyard#300]
We are using **shipyard 3.7.0** for running azure batch jobs using from only a few nodes up to a few hundreds. As input data our program needs about 1840 files which are 3,4 gb in size all together.

First we copy all the data to an Azure file storage and than let shipyard distribute the data to the nodes. Here we investigated a strange behaviour: When we use the Standard StorageV2 type of file storage, everything is ok and the length of the copy process is normal. What "normal" means depends on many things but most on the number of nodes. E.g. with 32 nodes, the copy process from the file storage to the nodes takes about six minutes.
After the tasks are completed only a few files are copied back from the node to the file storage. Right now the output data are five files with under one mb of size. This copy only takes seconds.

When using Azure Premuim File storage the behaviour is totally different: The copy from the file storage to the nodes take 30 minutes. But more important: The copy back from the nodes to the file storage after the tasks are run will stall. When you login to a node, the load avg is 197 on a 64 core machine and a lot of blobxfer processes are running with every process taking 100% cpu time.

So our impression is that shipyard has a issue with the Preium file storage.

**Comment by alfpark** [comment]
Premium file share is a provisioned performance offering that scales with capacity. You will need to modify the `blobxfer_extra_options` to ensure that you are not oversubscribing the throughput limits for any particular fileshare or file object. Please refer to the [jobs doc](https://github.com/Azure/batch-shipyard/blob/master/docs/14-batch-shipyard-configuration-jobs.md) regarding this option. You can also enable [Azure Storage metrics](https://docs.microsoft.com/azure/storage/common/storage-monitor-storage-account) on your storage account to observe the behavior.

Azure storage blob typically performs better for larger scale deployments with the recent improvements to that service (including better concurrency across multiple distinct downloaders and HTBB for upload).

Other resources:

* Blobxfer CLI doc: https://github.com/Azure/blobxfer/blob/master/docs/10-cli-usage.md
  * You can enable azure storage logging to see if you observe backoff/retries due to throttling. The logs may be potentially very verbose.
* Blobxfer perf considerations doc: https://github.com/Azure/blobxfer/blob/master/docs/98-performance-considerations.md
* Azure storage scalability and performance targets (with obvious attention to the premium file sections): https://docs.microsoft.com/azure/storage/common/storage-scalability-targets

**Comment by borisklug** [comment]
Thank you for your reply.  Thats excactly what happend here: We get a lot of throttling errors while data is copied. For me, switching to blob storage seems to be the best way for us.

I close this issue because its not an shipyard thing, more a wrong/missing understanding on our side.
