### ISSUE TITLE
Autoscale error with auto_scratch

### ISSUE THREAD

**Issue by freebo** [Azure/batch-shipyard#319]
#### Problem Description
With pool nodes defined as follows:

  vm_count:
    dedicated: 0
    low_priority: 0
  autoscale:
    evaluation_interval: 00:05:00
    scenario:
      name: active_tasks
      maximum_vm_count:
        dedicated: 0
        low_priority: 2
  vm_size: STANDARD_H16R

When attempting to run a job containing

auto_scratch: true

Error "NumInstances should be greater than 0 and less than or equal to 100"

Removing auto_scratch causes the job to be submitted sucessfully 
#### Batch Shipyard Version
3.82

#### Steps to Reproduce
Set nodes and auto_scatch paramaters as above

#### Expected Results
Job submitted

#### Actual Results
Error produced

#### Redacted Configuration
```


[of.tar.gz](https://github.com/Azure/batch-shipyard/files/3753535/of.tar.gz)

```

#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
`auto_scratch` is not fully supported/intended to be used with autoscale pools.

The fundamental issue is that auto scratch has to be set up on a per-job basis so at the time of job creation, it uses the number of nodes available to construct the distributed scratch space. Since your pool has no nodes by default, you're receiving this error. Additionally, if you mix `auto_scratch` with autoscale pools, because the setup task runs as a Batch task, there's a race condition where if the autoscale evaluation happens in between the `auto_scratch` setup task and when the tasks in the tasks array are added, your pool could begin scaling down, which would provide for a poor experience.

I will clean up the error messaging and add this to the limitations doc.
