### ISSUE TITLE
libreadline.so.6: no version information available (required by /bin/sh)

### ISSUE THREAD

**Issue by maroony** [Azure/batch-shipyard#338]
#### Problem Description

Every time shipyard is running, it prints the warning

```
/bin/sh: /tmp/_MEIxcaKuF/libreadline.so.6: no version information available (required by /bin/sh)
```

I'm using the binary `batch-shipyard-3.9.1-cli-linux-x86_64` on Suse Linux Enterprise Server 12.

#### Batch Shipyard Version
3.9.0, 3.9.1

#### Steps to Reproduce
Type `shipyard --version`

#### Expected Results
No warning message.

**Comment by alfpark** [comment]
Does this warning impact the execution (i.e., cause incorrect results)?

I believe this is due to packaging occurring on Ubuntu 18.04. As per the installation doc, the binary may not be fully compatible with all Linux distributions. In that case, the recommendation is to install via install script or use the CLI Docker image.

**Comment by maroony** [comment]
No, it doesn't impact the execution. It's only an annoying warning.

**Comment by alfpark** [comment]
Closing this as there's no execution impact and there are alternative installation/execution methods available to avoid the warning.
