### ISSUE TITLE
Will shared data volumes defined in config.json be shared across pools?

### ISSUE THREAD

**Issue by pareshverma91** [Azure/batch-shipyard#34]
From the documentation at https://github.com/Azure/batch-shipyard/blob/master/docs/10-batch-shipyard-configuration.md#global-config, it is not clear if the "shared_data_volumes", say e.g. GlusterFS setup, will be available across different pools created with the same config.json.

I haven't tried it out yet, but it seems that the volumes would only be available within a pool, in which case shouldn't the configuration exist in pool.json?

**Comment by alfpark** [comment]
@pareshverma91 GlusterFS volumes (right now) are only restricted to a single pool.

The configuration is broken up to be composable rather than bound to an entity. This allows you to mix and match a pool specification with different configurations of docker images or global resources (like shared data volumes).

Adding support for disparate GlusterFS (DFS) clusters or HDFS is something that's on the roadmap.
