### ISSUE TITLE
Question: should additional_node_prep_commands happen after input data commands?

### ISSUE THREAD

**Issue by artsobolev** [Azure/batch-shipyard#63]
Currently, `convoy/fleet.py` [adds additional start tasks](https://github.com/Azure/batch-shipyard/blob/master/convoy/fleet.py#L834) right before setting up any file shares, which makes it impossible to use fileshares during setup in the start task.

Wouldn't it make more sense to run `additional_node_prep_commands` after the shares are set up?

**Comment by alfpark** [comment]
@artsobolev node prep commands are part of the traditional Azure Batch start task. If you are referring to the Azure file docker volume plugin, that is setup prior to the execution of any of these additional node prep commands.

Note that Azure file shares are provided through the docker volume plugin and thus are not visible on the host.

Can you further elaborate the scenario for which you're using `additional_node_prep_commands` and file shares?

**Comment by artsobolev** [comment]
I'm not super familiar with the azure environment, so please forgive me if I use the wrong words.

What I want to do is basically to install a custom `whl` on each node before executing any jobs. The `whl` is located on a file share storage that's "mounted" via `pool_specification`'s `input_data`, and then referred to in the `additional_node_prep_commands`. Basically, I want to write some like this in the `pool.json`

        "input_data" : {
            "azure_storage": [{
                "storage_account_settings": "mystorageaccount",
                "file_share": "shared-source",
                "destination": "$AZ_BATCH_NODE_SHARED_DIR/"
            }]
        },
        "additional_node_prep_commands" : [
                "python -m pip install \"$AZ_BATCH_NODE_SHARED_DIR/package.whl\""
            ]

I guess I could just bundle a custom docker image with the package installed, but I found this solution (after I hacked the start task a bit) to be easier to implement in my case.

**Comment by alfpark** [comment]
For this case, yes, I think it's valid. In fact looking at the fleet code, the additional node prep commands should always run last. I can generate a fix for this and will be included in the next release (2.6.0b3).

Just clarify, you can think of `input_data` as physically moving bits from the source you specified (in this case your `mystorageaccount/shared-source` fileshare to `$AZ_BATCH_NODE_SHARED_DIR`.

Mounting your file share is accomplished in `config.json` as a `shared_data_volume`. However, as noted above, this would require some additional hoop jumping since Azure File shares aren't visible on the host - you need to move the data as you have done in `input_data`.
