### ISSUE TITLE
question - Infiniband job isolation

### ISSUE THREAD

**Issue by hopoffbaby** [Azure/batch-shipyard#67]
Hi All,

Is it possible to use shipyard to run multiple jobs in the same pool and have each job isolated from each other in terms of networking and storage.

For example, can I map in a specific data area for each job that is not accessible to other jobs running in the same pool and potentially on the same node.

Also, I note that enabling infiniband forces docker to use the hosts networking stack. Does this means that all containers can communicate with each other even if they are part of another job but in the same pool?

Thanks,
h

**Comment by hopoffbaby** [comment]
Just to add, the reason being is I have to consider all data and files for each job potentially malicious. 

Thanks,
h

**Comment by alfpark** [comment]
@hopoffbaby For infiniband, this is currently not possible since containers use the host networking stack (there may be a way to bridge the IB network interface, but I'm not sure how that would work). With recent versions of Docker (certainly versions installed by Batch Shipyard), filesystem safety between running containers is a reasonable expectation (if you are not mounting shared host directories into the container and are not exposing the docker socket into the container). You can further isolate by using user namespaces via the user identity properties available.

In general, if you are targeting for hostile multi-tenancy, pure non-virtualized Docker containers is the wrong model. Pool boundaries are the proper isolation level between users. Right now, there is no support for "thin-VMs + containers" in Azure suitable for hostile multi-tenancy.

**Comment by alfpark** [comment]
Closing, please re-open if you have additional questions about this topic.
