### ISSUE TITLE
Suggestion for speed up shipyardrf container deletion when starting up new pool

### ISSUE THREAD

**Issue by lediur** [Azure/batch-shipyard#80]
If I delete a pool using the Azure portal, I noticed that Batch Shipyard does some cleanup of the lingering Shipyard-specific blob containers when I call the `pool add` command for that pool. Some of these steps take quite a long time to complete if the old pool deployed a lot of tasks or jobs. For example, deleting blobs for one of my pool's `shipyardrf` container takes almost 15 minutes to finish up, and the lack of progress sometimes makes me wonder if it's hung or not.

Since the container is being completely emptied anyways, maybe it makes sense to delete the container and recreate it instead of iterating through all of the blobs and deleting them? As an end user, it seems like container deletion is almost instantaneous, whereas deleting blobs is a one-by-one ordeal.

**Comment by alfpark** [comment]
Unfortunately, the restriction of `pool del` was left out of the current limitations doc. Deleting a pool out-of-band is "not supported." As you have experienced, it does actually work since this logic was put in specifically to work around cases where pool deletion is done out-of-band since it is bound to happen.

The reason it's done via clear instead of container delete is that container deletion is not instantaneous. Deletion followed by creation can result in 409 conflicts with non-deterministic wait time. I think having that many tasks per pool may be the exception and not the common case.

What you can do instead is (ensure you have the proper `pool.json` loaded):
`shipyard storage del`
`shipyard pool add`

You may get table/blob/queue creation conflict errors here. Just keep retrying `shipyard pool add` until there are no storage-related errors.

The best way to avoid this is to just use `shipyard pool del` to delete your pools.

I will add the option `--clear-tables` to:
`shipyard storage del --clear-tables`

which will delete all storage containers related to the `pool.json` specified except for tables, and will only clear those. This is roughly what `pool del` will do with storage except not deleting the pool as well.
