### ISSUE TITLE
Request for not introducing breaking change related to vm_count

### ISSUE THREAD

**Issue by sebastianbk** [Azure/batch-shipyard#84]
I am a little concerned by the proposed breaking change related to `vm_count` in the `pool` specification. I understand the desire to support low priority nodes but I do not see the need for making the change a breaking one.

Can it not be made so that the `vm_count` item can either be an `int` or a `dict`? If the user provides an `int` you could simply construct a `dict` with the `dedicated` item being equaled to the supplied value. In my opinion, that would be a lot cleaner.

We have got quite a lot of recipes in production and I would hate to go a change every single one whenever a new feature has been added to Azure Batch.

**Comment by sebastianbk** [comment]
I submitted a pull request regarding this issue (#85).

**Comment by alfpark** [comment]
Batch Shipyard will always progress with new features being released with the Batch service. If you need to lock in your deployments, you can always do so by using the CLI for the version that you deployed with. Conceptually, this is no different from a new SDK being released that introduces breaking changes. For instance, if you do not want the 2.7.0b1 changes, you can just use the 2.6.2 CLI either with the provided Docker image with that tag or by doing a git checkout to the 2.6.2 tag. This will allow you can upgrade at your own convenience and not be subject to whatever is in `master` or the latest release.

Batch Shipyard will evolve rapidly with both Azure Batch API changes and potential future features - preserving backward compatibility at every release is not a primary goal (although we will try our best to prevent such changes for "patch" level releases). I think versioned releases and the ability to deploy bound to a specific release is a good middle ground. I hope this makes sense and have a better understanding of the intent and priorities for this project.

For the specific `vm_count` change, I can explore the possibility of a deprecation path forward since it is an inconvenient change for a "minor" release. However, this would only be supported for a few releases then dropped.

**Comment by sebastianbk** [comment]
I see. But I must say that I disagree. We are talking about a 5-loc fix for this. I do not think it's fair to say that customers must be stuck on some mid-level release if they are not willing to invest potentially a lot of time in updating their configs in order to update to the latest version. Microsoft has always been committed to backward compatibility and even though development of cloud products is going faster than what we are used to in traditional software products, I do not think it's a valid excuse for not being committed to continuously supporting customers.

If you are worried about building up a cluttered code base over the long run due to the inevitable growing pile of backward compatibility fixes, I suggest separating out these fixes into its own module. That way the core functionality would not be affected.

I used to work for Microsoft as a Consultant in Enterprise Services and as an Evangelist in DX. Being out in the field and dealing with customers that make valid complaints about breaking changes on a continuous basis was a hassle my colleagues and I had to go through almost every day. In many cases it would not take a big effort from the respective product group to facilitate the fix required for not making the proposed changes breaking ones.

Anyway, I hope you will consider this when developing new features going forward.

**Comment by alfpark** [comment]
For this particular `vm_count` issue, a deprecation path was added in case you missed the commit added to this issue.

There are all valid points and good feedback. Did you have an expectation that a .minor release would not involve a breaking change? If so, then we'll need to clarify this in the documentation. In any case, we'll do a better job of either communicating such breaking changes earlier and/or adding in deprecation paths. However, we won't be maintaining these paths for long periods of time. Separating out these may not be as simple as this `vm_count` change for future modifications (e.g., the upcoming `blobxfer` changes will fundamentally change the schema, code paths and scripts because the tool itself is being rewritten).

I must re-iterate that this project is not intended to provide 100% backward-compatible configuration between every major/minor release, although with patch-level releases we will try to avoid such breaking changes. This project tracks against the Azure Batch SDK and things may change. Batch Shipyard has hidden a lot of these breaking changes in the past because it is configuration driven, but certain features may need to change the configuration itself. You should certainly expect breaking changes to happen on major releases as we push the boundary on what capabilities are added at the intersection of Azure Batch, HPC, containerization and other topics. We want to iterate quickly and deliver solutions that are not currently possible out-of-the-box with Azure Batch alone - unfortunately this may require a breaking change here or there.
