### ISSUE TITLE
Jobs with no more tasks do not enter completed state

### ISSUE THREAD

**Issue by andreadotti** [Azure/batch-shipyard#96]
When a job finishes all his tasks, it is still marked as active thus counting for the quota of the batch account.
While this is a minor issue, it requires monitoring the jobs looking for finished jobs and manually delete them submit new jobs when quota is reached.

Is there a way to automatically set a job status to "Completed" when a job finishes all of its tasks?

**Comment by alfpark** [comment]
Jobs do not automatically complete by default since Azure Batch has no idea if the user will be adding more tasks to the job in the future. However, there is an auto-completion feature which you can enable. Please consult the [jobs configuration documentation](https://github.com/Azure/batch-shipyard/blob/master/docs/14-batch-shipyard-configuration-jobs.md) and search for `auto_complete`.

**Comment by andreadotti** [comment]
Thanks, my bad to have missed that.
